trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'terraform_service_connection'
  workingDirectory: 'environments/dev'

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: azurerm
    command: init
    workingDirectory: $(workingDirectory)
    backendServiceArm: $(serviceConnection)
    backendAzureRmResourceGroupName: rg-terraform-state
    backendAzureRmStorageAccountName: statefilebackupaccounts
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: dev.tfstate

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: azurerm
    command: plan
    workingDirectory: $(workingDirectory)
    environmentServiceNameAzureRM: $(serviceConnection)
    commandOptions: '-var-file=myvars.tfvars'

- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: azurerm
    command: apply
    workingDirectory: $(workingDirectory)
    environmentServiceNameAzureRM: $(serviceConnection)
    commandOptions: '-var-file=myvars.tfvars -auto-approve' 